config/routes.rb
Rails.application.routes.draw do
  resources :books

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"

  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, :only => [:show, :edit, :update, :destroy]

  def index
    @books = Book.page(params[:page]).per(5)
    @book = Book.new
  end

  def show
    @page_title = @book.name
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "編輯成功"
      redirect_to book_path(@book)
    else
      render :action => :edit
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new (book_params)

    if @book.save
      flash[:notice] = "Add new book!!!!!!!!!!!!!!!!!"
      redirect_to books_path
    else
      render :action => :new
    end
  end

  def destroy
    flash[:alert] = "dare u kill me!!!!!!!"
    @book.destroy
    redirect_to  books_path
  end



private
  def book_params
    params.require(:book).permit(:name, :description, :isbn, :publicatino_date, :date_added)
  end

  def set_book
    @book = Book.find(params[:id])
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def say
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/edit.html.erb
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <%end%>
    </ul>
  <%end%>

  <div class="form-group">
    <%= f.label :name, "Book's Title" %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :isbn, "ISBN" %>
    <%= f.number_field :isbn, :class => "form-control" %>
  </div>

  <div class="form-froup">
    <%= f.label :publication_date, "publication_date" %>
    <%= f.date_select :publication_date, :class => "form-control" %>
  </div>

  <div class="form-froup">
    <%= f.label :date_added, "date_added" %>
    <%= f.datetime_select :date_added, :class => "form-control" %>
  </div>

  <%= f.submit "Update", :class => "btn btn-primary" %>

<%end%>

app/views/books/index.html.erb
<h1>Book List</h1>

<table class="table">
  <% @books.each do |i|  %>
    <tr>
      <td><%= i.name %></td>
      <td>
        <%= link_to 'show', book_path(i), :class => "btn btn-primary" %>
        <%= link_to 'edit', edit_book_path(i), :class => "btn btn-info" %>
        <%= link_to 'Delete', book_path(i), :method => :delete, :class => "btn btn-danger" %>
      </td>
    </tr>
  <%end%>
</table>

<h2>Add new books here</h2>
<%= paginate @books %>

<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <%end%>
    </ul>
  <%end%>

  <div class="form-group">
    <%= f.label :name, "Book's Title" %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :isbn, "ISBN" %>
    <%= f.number_field :isbn, :class => "form-control" %>
  </div>

  <div class="form-froup">
    <%= f.label :publication_date, "publication_date" %>
    <%= f.date_select :publication_date, :class => "form-control" %>
  </div>

  <div class="form-froup">
    <%= f.label :date_added, "date_added" %>
    <%= f.datetime_select :date_added, :class => "form-control" %>
  </div>

  <%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>
<h4>About this book: </h4><%= simple_format @book.description %>
<h4>ISBN:</h4> <%= @book.isbn %>
<h4>Publication date: </h4> <%= @book.publication_date %>
<h4>Date added: </h4><%= @book.date_added %>
<p><%= link_to 'back to index', books_path, :class => "btn btn-primary" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "BookProject" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <% if flash[:notice].present? %>
          <div class="alert alert-success" role="alert">
            <%= flash[:notice] %>
          </div>
          <%end%>

          <% if flash[:alert].present? %>
            <div class="alert alert-danger" role="alert">
            <%= flash[:alert] %>
          </div>
          <%end%>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<p>Bonsoir~ it's <%= Time.now %></p>
<p><%= link_to 'bonjour!', welcome_say_hello_path  %></p>

app/views/welcome/say.html.erb
<h1>bonjour!</h1>
<p><%= link_to "Home", root_path %></p>